### ISSUE TITLE
Resolve connectivity issues with default Multus networks on the OpenShift test setup

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-kubevirt#32]
When using an OpenShift cluster as a provider cluster, we are so far not able to perform a successful test with a default Multus network, following the recommendations we got so far.

The default Multus network uses the `whereabouts` CNI plugin with the following configuration:

```json
{
  "cniVersion": "0.3.0",
  "name": "whereabouts",
  "type": "bridge",
  "bridge": "br1",
  "ipam": {
    "type": "whereabouts",
    "range": "10.194.136.0/24"
  }
}
```

When the VM starts, we see the network interface having the correct IP address. However, the `cloud-init` fails due to the VM being unable to connect to the Internet with errors similar to:

```
[  235.670490] cloud-init[1054]: W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
```

/area networking
/kind task
/priority normal
/platform kubevirt

**Comment by stoyanr** [comment]
After a discussion with @rootfs, we got the following ideas how to resolve the issue:

We should be able to use a two more CNI plugins: `firewall` and `route-override`. Firewall makes iptable rules on the host so the VM egress traffic can be routed to the host. Route-override is to update host's routing table. @rootfs tested firewall CNI and did some manual routing table configuration, see https://gist.github.com/rootfs/a69749b0d69f282ba9e14dd48d940a04. The next step would be to figure out the CNI plugin chains and how to set the parameters right.

The two CNIs are:
* [route-override](https://github.com/redhat-nfvpe/cni-route-override)
* [firewall](https://github.com/containernetworking/plugins/tree/master/plugins/meta/firewall)

**Comment by mfranczy** [comment]
hey @rootfs what about vlan solution we spoke?

**Comment by stoyanr** [comment]
A solution was proposed and documented by @rootfs, see https://gist.github.com/rootfs/0069f7dd3df0e72eb8323bff44744e6a.

**Comment by stoyanr** [comment]
@rootfs I am trying to build a cluster using the Multus configuration from https://gist.github.com/rootfs/0069f7dd3df0e72eb8323bff44744e6a

```
{
  "cniVersion": "0.4.0",
  "name": "my-whereabouts",
  "type": "bridge",
  "bridge": "br-vxlan10",
  "vlan": 1234,
  "ipam": {
    "type": "whereabouts",
    "range": "10.123.124.0/24",
    "range_start": "10.123.124.4",
    "range_end": "10.123.124.200",
    "routes": [
        { "dst": "0.0.0.0/0", "gw" : "10.123.124.1" }
    ]
  }
}
```

as the default network. Unfortunately, the `cloud-init` fails as names can't be resolved:

```
Cloud-init v. 20.3-2-g371b392c-0ubuntu1~18.04.1 running 'modules:config' at Fri, 25 Sep 2020 15:28:51 +0000. Up 54.01 seconds.
[   93.871329] cloud-init[1048]: Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
[   93.876022] cloud-init[1048]:   Temporary failure resolving 'security.ubuntu.com'
```

**Comment by stoyanr** [comment]
As advised by @rootfs, I also tried with:

```yaml
{
  "cniVersion": "0.4.0",
  "name": "my-whereabouts",
  "type": "bridge",
  "bridge": "br-vxlan10",
  "vlan": 1234,
  "ipam": {
    "type": "whereabouts",
    "range": "10.123.124.0/24",
    "range_start": "10.123.124.4",
    "range_end": "10.123.124.200",
    "routes": [
        { "dst": "0.0.0.0/0", "gw" : "10.123.124.1" }
    ],
    "dns": {
      "nameservers": [ "8.8.8.8" ],
      "domain": "example.com",
      "search": [ "example.com" ]
    }
  }
}
```

Unfortunately with the same result as before. We suspect this is a bug in Kubevirt, and opened the following issue: https://github.com/kubevirt/kubevirt/issues/4267.
