### ISSUE TITLE
Add proper support for region and zone

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-kubevirt#40]
When using provider clusters with multiple regions and zones, we should be able to pass the shoot `region` and the worker pool `zone` to the VM spec, so that VMIs are scheduled on provider cluster nodes with the specified region / zone. This should be possible via the `spec.affinity` field as described in [Affinity and anti-affinity](https://kubevirt.io/user-guide/#/usage/node-placement?id=affinity-and-anti-affinity), specifically via the `spec.affinity.nodeAffinity` field:

```yaml
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.beta.kubernetes.io/region
            operator: In
            values:
            - <region>
          - key: failure-domain.beta.kubernetes.io/zone
            operator: In
            values:
            - <zone>
```

**Note:** The Kubevirt CCM already correctly propagates the provider node labels `failure-domain.beta.kubernetes.io/region` and `failure-domain.beta.kubernetes.io/zone` to the shoot cluster node.

/area high-availability
/kind enhancement
/priority normal
/platform kubevirt
