### ISSUE TITLE
Make pre-allocated data volumes configurable

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-kubevirt#56]
The support for pre-allocated data volumes introduced with #17 is currently not configurable - a pre-allocated data volume is always created when a new machine class is created, and then used by VMs based on that machine class. It would be better to make this feature configurable. There are 2 options:

1. In the `providerConfig` section of the cloud profile - in this case, it would be applicable to all machines of the corresponding type:

```yaml
  providerConfig:
    apiVersion: kubevirt.provider.extensions.gardener.cloud/v1alpha1
    kind: CloudProfileConfig
    machineTypes:
    - name: "standard-1"
      dontUsePreallocatedDataVolumes: true
```

2. In the `providerConfig` section of the shoot worker - in this case, it could be specified per individual shoot / worker:

```yaml
workers:
- name: cpu-worker
  machine:
    type: standard-1
    ...
  providerConfig:
    apiVersion: kubevirt.provider.extensions.gardener.cloud/v1alpha1
    kind: WorkerConfig
    dontUsePreallocatedDataVolumes: true
```

After a discussion we decided that we prefer option 2. By default, pre-allocated data volumes should be "on", so the setting is `dontUsePreallocatedDataVolumes` should have `false` as default.

/area storage
/kind enhancement
/platform kubevirt
/priority normal
