### ISSUE TITLE
Add support for volume types and adding non-root disks to shoot workers

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-kubevirt#68]
In addition to being able to specify `storage` for each machine type in the cloud profile, we should support being able to define `volumeTypes` in the cloud profile, and then use the defined volume types to specify the root disk as worker `volume` in the `Shoot` resources. The defined volume types can also be used to specify additional `dataVolumes`, or non-root disks, for shoot workers.

Example `CloudProfile` resource with `volumeTypes`:
 
```yaml
spec:
  type: kubevirt
  ...
  volumeTypes:
  - name: cephrbd
    class: ocs-storagecluster-ceph-rbd
    usable: true
```

Example `Shoot` resource using the defined volume type for a root disk volume and for an additional data volume:

```yaml
spec:
  provider:
    type: kubevirt
    workers:
    - name: worker1
      volume:
        type: cephrbd
        size: 20Gi
        encrypted: false
      dataVolumes:
      - name: volume1
        type: cephrbd
        size: 25Gi
        encrypted: false
      ...
```

When used as a root disk, the volume type in Kubevirt should always be `dataVolume`, since it needs an OS image. When used as a non-root disk, the volume type in Kubevirt should be `persistentVolumeClaim`. We could also make this type configurable via the `providerConfig` section of the cloud profile, but this is not considered very important and could also be done later. In this case, the `CloudProfile` resource would look as follows:

```yaml
spec:
  type: kubevirt
  providerConfig:
    apiVersion: kubevirt.provider.extensions.gardener.cloud/v1alpha1
    kind: CloudProfileConfig
    ...
    volumeTypes:
    - name: cephrbd-ephemeral
      type: ephemeral
  ...
  volumeTypes:
  - name: cephrbd-ephemeral
    class: ocs-storagecluster-ceph-rbd
    usable: true
```

For the complete list of volume types supported by Kubevirt, see https://kubevirt.io/api-reference/master/definitions.html#_v1_volume.

In the `Shoot` example above, `encrypted` could be omitted as it defaults to `false`, and setting it to `true` would not be possible as this is not something we could support uniformly across different storage providers. However, depending on the storage provider, encryption could still be enabled for the some of the storage classes used, see for example  [how to do it for Ceph RBD](https://github.com/ceph/ceph-csi/blob/master/docs/deploy-rbd.md).

/area storage
/kind enhancement
/priority normal
/platform kubevirt
