### ISSUE TITLE
Add support for specifying `networkData` as part of the worker config

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-kubevirt#69]
Currently, Kubevirt VM `networkData` is hardcoded in https://github.com/gardener/machine-controller-manager-provider-kubevirt to the following YAML snippet if custom networks are used, and to an empty string otherwise:

```yaml
version: 2
ethernets:
  id0:
    match:
      name: "e*"
    dhcp4: true
```

We should be able to specify the `networkData` in the `Shoot` resource as part of the worker config, as it could be used to configure other networking aspects beyond DHCP the could be important in certain cases. See [Networking Config Version 2](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html) for the full documentation.

Example `Shoot` resource with `networkData` configured:

```yaml
spec:
  provider:
    type: kubevirt
    workers:
    - name: worker1
      ...
      providerConfig:
        apiVersion: kubevirt.provider.extensions.gardener.cloud/v1alpha1
        kind: WorkerConfig
        networkData: |
          <...>
```

/area networking
/kind enhancement
/priority normal
/platform kubevirt
